---
- hosts: www
  gather_facts: False

  vars:
    root_dir: "{{ playbook_dir }}"
    shared_dir: "{{ playbook_dir }}/../shared"


  pre_tasks:
    - ansible.builtin.debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python fallback if needed
      raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      become: true

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      ansible.builtin.apt: pkg="acl"
      become: true

    - name: gather facts
      setup:

    - name: Check for common pretasks
      local_action: stat path="{{shared_dir}}/common_pretasks.yml"
      register: common_pretasks_exists
      tags: always

    - name: Include common pretasks
      ansible.builtin.include_tasks: "{{shared_dir}}/common_pretasks.yml"
      when: common_pretasks_exists.stat.exists == true
      tags: always


  roles:

    - {
        role: "sa_webhook_helper"
      }


  tasks:

    - ansible.builtin.debug: msg="Tasks section"

