---
- name: Configure webhook server
  hosts: www
  gather_facts: false

  vars:
    root_dir: "{{ playbook_dir }}"
    shared_dir: "{{ playbook_dir }}/../shared"

  pre_tasks:
    - name: Display pre-tasks message
      ansible.builtin.debug:
        msg: "Pre tasks section"

    - name: ANSIBLE PYTHON | install python fallback if needed
      ansible.builtin.raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python-minimal)
      changed_when: false
      become: true

    - name: UNPRIVILEGED USERS | Get acl dependency
      ansible.builtin.apt:
        name: acl
      become: true

    - name: Gather facts
      ansible.builtin.setup:

    - name: Check for common pretasks
      ansible.builtin.stat:
        path: "{{ shared_dir }}/common_pretasks.yml"
      delegate_to: localhost
      register: common_pretasks_exists
      tags: always

    - name: Include common pretasks
      ansible.builtin.include_tasks: "{{ shared_dir }}/common_pretasks.yml"
      when: common_pretasks_exists.stat.exists
      tags: always

  roles:
    - role: sa_webhook_helper

  tasks:
    - name: Display tasks message
      ansible.builtin.debug:
        msg: "Tasks section"
